@startuml
title RemoveBookFromCatalog

actor Client
participant "Load Balancer/ECS" as LoadBalancerECS
participant RemoveBookFromCatalogActivity
participant CatalogDao
database DynamoDB









@enduml
